moltin/gatsby-demo-store

- package.json
- src/components/AddToCart.js
- src/components/Badge.js
- src/components/Product.js
- src/components/Promotion.js
- src/shopkit/index.js
- src/templates/ProductPage.js
- yarn.lock
Adds `X in stock`, `Out of stock` badges to product page.
> feat: Product inventory availability

- src/hooks/useMoltinInventory.js
- src/templates/ProductPage.js
Refactors inventory lookup to a custom hook.
> refactor: Add custom hook to fetch product inventory

- gatsby-config.js
- src/components/Category.js
- src/pages/products.js
- src/templates/CategoryPage.js
- src/templates/ProductPage.js
Unless the store uses flows, this starter has a high barrier to get up and running.
> Remove all flows references

- src/pages/checkout.js
- src/validation/payment.js
- src/validation/shipping.js
Closes FRONT-230
~Branch named `chore`. Git fail.~
> feat: introduce multistep wizard

- package.json
- yarn.lock
> chore: Remove rimraf devDependency

- package.json
- src/context/CheckoutContext.js
- src/pages/checkout.js
This PR adds basic stripe intents API functionality.
> feat: stripe intents checkout

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Add initial github PR template file 
- Add initial github contribution template file 
- Add initial github issue template file
> feat: Github template md files

- gatsby-config.js
* ### Feature
- Re-enable Algolia search with new index
* ### Fix
* ### Docs
* ### Style
* ### Refactor
* ### Performance
* ### Test
* ### Chore
* Fixes [MT-]
> feat: Re-enable Algolia search

- src/components/Layout/Header.js
- src/context/CustomerContext.js
- src/pages/checkout.js
- src/pages/profile.js
* ### Feature
This PR adds Profile page with ability to view and update user info. And autofill user info on the Checkout page
> feat: Profile page

- gatsby-node.js
- src/components/Layout/Footer.js
- src/components/Layout/Layout.js
- src/images/arrow_down.svg
In this PR: the data structure of categories was rebuilt and subcategories are displayed as a dropdown in the footer.
> feat: category navigation

- src/components/AddressFields.js
- src/components/SideMenu.js
- src/context/CheckoutContext.js
- src/context/CustomerContext.js
- src/pages/addresses.js
- src/pages/checkout.js
- src/pages/profile.js
- src/validation/address.js
* ### Feature
This PR adds the ability to add addresses on Address Book page and select them on the Checkout page
> Feat: Address selection

- README.md
* ### Feature
* ### Fix
* ### Docs
- Doc updates for branding
* ### Style
* ### Refactor
* ### Performance
* ### Test
* ### Chore
* Fixes N/A
> docs: README Branding Update

- src/components/Layout/Footer.js
- src/pages/about.js
- src/pages/index.js
* ### Feature
- Site-wide rebranding
* ### Fix
* ### Docs
* ### Style
* ### Refactor
* ### Performance
* ### Test
* ### Chore
* Fixes [MT-]
> Feat: Site-wide rebranding

- package.json
- src/context/useLocalStorage.js
- src/pages/index.js
* ### Chore
Changes to the build process or auxiliary tools and libraries such as documentation generation  
Add lint staged to keep formatting consistent and PRs easier 👍
> chore: add lint-staged and run prettier

- gatsby-node.js
- package.json
- src/components/AddToCart.js
- src/components/RadioButton.js
- src/components/VariationOptions.js
- src/components/VariationSelector.js
- src/components/VariationsSelector.js
- src/context/useLocalStorage.js
- src/templates/ProductPage.js
- yarn.lock
* ### Feature
Added support for product variations
> feat: product variations

- src/components/Category.js
- src/components/SEO.js
- src/components/VariationOptions.js
Fixed issue with SEO and Category component in case image, not present
> fix: seo and category image issue

- src/components/SideMenu.js
- src/context/CustomerContext.js
- src/images/arrow_left.svg
- src/pages/checkout.js
- src/pages/orderdetails.js
- src/pages/orders.js
- src/pages/profile.js
* ### Feature
This PR adds Orders page and Order Details page
* Fixes [MT-]
> feat: Orders page

- README.md
* ### Feature
* ### Fix
* ### Docs
- README doc update
* ### Style
* ### Refactor
* ### Performance
* ### Test
* ### Chore
* Fixes [MT-]
> README doc update

- gatsby-node.js
- src/templates/CategoryPage.js
- src/templates/CollectionPage.js
- src/templates/ProductsList.js
* ### Feature
Filters out child products from the graphql. Child product pages will not be created and therefore will not be displayed. This was needed for signatur catalog which had about 50 parent products and 200 child products.
> [Feature] Filter product variations (child products) from Product Listing

- gatsby-config.js
* ### Feature
Rebrand the site description
Updates the site description that appears from site previews.
* Fixes [MT-]
> Update site description that is shown in site preview
